FROM node:22-alpine

WORKDIR /app

RUN apk add --no-cache openssl

COPY package.json yarn.lock ./
RUN yarn install

COPY . .

RUN npx prisma generate
RUN yarn build

EXPOSE 4000

CMD ["sh", "-c", "yarn db:migrate-prod && yarn start"]
