FROM node:22-alpine

WORKDIR /app

RUN apk add --no-cache openssl

COPY package.json yarn.lock ./
RUN yarn install

COPY . .

RUN DATABASE_URL=postgresql://build:build@localhost:5432/build yarn build

EXPOSE 4000

CMD ["sh", "-c", "yarn db:migrate-prod && yarn start"]
