export const ErrorCode = {
  TOKEN_MISSING: 'TOKEN_MISSING',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  TOKEN_REVOKED: 'TOKEN_REVOKED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EMAIL_EXISTS: 'EMAIL_EXISTS',
  SPACE_NAME_EXISTS: 'SPACE_NAME_EXISTS',
  SPACE_NOT_FOUND: 'SPACE_NOT_FOUND',
  NOTE_NOT_FOUND: 'NOTE_NOT_FOUND',
  NOTE_CONTENT_EMPTY: 'NOTE_CONTENT_EMPTY',
  NOTE_CONTENT_TOO_LONG: 'NOTE_CONTENT_TOO_LONG',
  INTERNAL_ERROR: 'INTERNAL_ERROR'
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
