export const ErrorCode = {
  TOKEN_MISSING: 'TOKEN_MISSING',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  TOKEN_REVOKED: 'TOKEN_REVOKED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EMAIL_EXISTS: 'EMAIL_EXISTS',
  SPACE_NAME_EXISTS: 'SPACE_NAME_EXISTS',
  SPACE_NOT_FOUND: 'SPACE_NOT_FOUND',
  NOTE_NOT_FOUND: 'NOTE_NOT_FOUND',
  NOTE_CONTENT_EMPTY: 'NOTE_CONTENT_EMPTY',
  NOTE_CONTENT_TOO_LONG: 'NOTE_CONTENT_TOO_LONG',
  NOTE_ALREADY_CONVERTED: 'NOTE_ALREADY_CONVERTED',
  SOURCE_NOT_FOUND: 'SOURCE_NOT_FOUND',
  SOURCE_NOT_FAILED: 'SOURCE_NOT_FAILED',
  INVALID_FILE_EXTENSION: 'INVALID_FILE_EXTENSION',
  INVALID_FILE_SIGNATURE: 'INVALID_FILE_SIGNATURE',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  FILE_UPLOAD_FAILED: 'FILE_UPLOAD_FAILED',
  EMBEDDING_FAILED: 'EMBEDDING_FAILED',
  NOTEBOOK_CONTENT_TOO_LONG: 'NOTEBOOK_CONTENT_TOO_LONG',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  MALFORMED_JSON: 'MALFORMED_JSON',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  INTERNAL_ERROR: 'INTERNAL_ERROR'
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
